version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: arreos-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@Admin
      POSTGRES_DB: arreos_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - arreos_pgdata:/var/lib/postgresql/data
    networks:
      - arreos-network

  app:
    build: .
    container_name: arreos-web
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:123@Admin@db:5432/arreos_db?schema=public
      - JWT_SECRET=ca31b7c6b832ec140f18e5347a07fcaef3d0bb585eb6c1b22f34e43ae0d52b83
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - db
    networks:
      - arreos-network
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/community:/app/public/community

networks:
  arreos-network:
    driver: bridge

volumes:
  arreos_pgdata:
